import NativeCarrySpectralWeyl.Infinite.GramKernel
import Mathlib.Analysis.InnerProductSpace.Completion
import Mathlib.Analysis.InnerProductSpace.Subspace
import Mathlib.LinearAlgebra.Finsupp.Supported

/-!
# The canonical all-bases camera Hilbert space

The all-bases Gram kernel constructed in `Infinite.GramKernel` is strictly
positive on finitely supported camera coefficients.  This file uses that
result to equip the algebraic camera space `c₀₀` with its intrinsic real
inner product and then takes Mathlib's canonical uniform-space completion.

No external weight on camera labels is introduced.  The resulting Hilbert
space is the completion dictated by the asymptotic Gram covariance itself.
The finite levels consisting of cameras with label at most `B` embed
isometrically, and the union of all these finite-level images is dense.
-/

open scoped BigOperators RealInnerProductSpace

noncomputable section

namespace NativeCarrySpectralWeyl.Infinite

/-- Algebraic all-bases camera space: finitely supported real camera
coefficients. -/
abbrev CameraFinsupp := CameraIndex →₀ ℝ

/-- The Gram form is additive in its first variable. -/
theorem gramForm_add_left (u₁ u₂ v : CameraFinsupp) :
    gramForm (u₁ + u₂) v = gramForm u₁ v + gramForm u₂ v := by
  classical
  rw [gramForm, Finsupp.sum_add_index'] <;>
    simp [gramForm, add_mul, Finsupp.sum_add]

/-- The Gram form is additive in its second variable. -/
theorem gramForm_add_right (u v₁ v₂ : CameraFinsupp) :
    gramForm u (v₁ + v₂) = gramForm u v₁ + gramForm u v₂ := by
  rw [gramForm_comm, gramForm_add_left]
  simp only [gramForm_comm]

/-- The Gram form is homogeneous in its first variable. -/
theorem gramForm_smul_left (scalar : ℝ) (u v : CameraFinsupp) :
    gramForm (scalar • u) v = scalar * gramForm u v := by
  classical
  rw [gramForm, Finsupp.sum_smul_index] <;>
    simp [gramForm, Finsupp.mul_sum, mul_assoc]

/-- The Gram form is homogeneous in its second variable. -/
theorem gramForm_smul_right (scalar : ℝ) (u v : CameraFinsupp) :
    gramForm u (scalar • v) = scalar * gramForm u v := by
  rw [gramForm_comm, gramForm_smul_left]
  simp only [gramForm_comm]

/-- The Gram form vanishes when its first variable vanishes. -/
@[simp] theorem gramForm_zero_left (v : CameraFinsupp) :
    gramForm 0 v = 0 := by
  simp [gramForm]

/-- The Gram form vanishes when its second variable vanishes. -/
@[simp] theorem gramForm_zero_right (u : CameraFinsupp) :
    gramForm u 0 = 0 := by
  rw [gramForm_comm]
  exact gramForm_zero_left u

/-- The canonical coordinate vectors recover the all-bases Gram kernel. -/
@[simp] theorem gramForm_single_single (camera₁ camera₂ : CameraIndex)
    (coefficient₁ coefficient₂ : ℝ) :
    gramForm (Finsupp.single camera₁ coefficient₁)
        (Finsupp.single camera₂ coefficient₂) =
      coefficient₁ * gramKernel camera₁ camera₂ * coefficient₂ := by
  classical
  simp [gramForm]

/-- Positive-definite real inner-product core induced by the all-bases Gram
form. -/
@[implicit_reducible]
def cameraInnerProductCore : InnerProductSpace.Core ℝ CameraFinsupp where
  inner := gramForm
  conj_inner_symm u v := by
    simpa only [starRingEnd_apply, star_trivial] using gramForm_comm v u
  re_inner_nonneg := gramForm_nonneg
  add_left := gramForm_add_left
  smul_left u v scalar := by
    simpa only [starRingEnd_apply, star_trivial] using
      gramForm_smul_left scalar u v
  definite u hu := by
    by_contra hne
    exact (ne_of_gt (gramForm_pos hne)) hu

/-- Intrinsic normed additive-group structure generated by the all-bases Gram
form. -/
noncomputable instance instNormedAddCommGroupCameraFinsupp :
    NormedAddCommGroup CameraFinsupp :=
  @InnerProductSpace.Core.toNormedAddCommGroup ℝ CameraFinsupp _ _ _
    cameraInnerProductCore

/-- Intrinsic real inner-product structure generated by the all-bases Gram
form. -/
noncomputable instance instInnerProductSpaceCameraFinsupp :
    InnerProductSpace ℝ CameraFinsupp :=
  InnerProductSpace.ofCore cameraInnerProductCore.toCore

/-- The intrinsic inner product on `c₀₀` is exactly the all-bases Gram
form. -/
@[simp] theorem cameraFinsupp_inner_eq_gramForm (u v : CameraFinsupp) :
    inner ℝ u v = gramForm u v := rfl

/-- The square of the intrinsic `c₀₀` norm is its Gram quadratic form. -/
theorem cameraFinsupp_norm_sq (u : CameraFinsupp) :
    ‖u‖ ^ 2 = gramForm u u := by
  rw [InnerProductSpace.norm_sq_eq_re_inner (𝕜 := ℝ)]
  rfl

/-- Canonical all-bases camera Hilbert space: the completion of finitely
supported coefficients in the intrinsic Gram norm. -/
abbrev CameraHilbert := UniformSpace.Completion CameraFinsupp

/-- The canonical all-bases camera space is complete. -/
theorem cameraHilbert_isComplete_univ :
    IsComplete (Set.univ : Set CameraHilbert) :=
  complete_univ

/-- Canonical isometric embedding of finitely supported camera coefficients
into the all-bases camera Hilbert space. -/
def cameraEmbedding : CameraFinsupp →ₗᵢ[ℝ] CameraHilbert :=
  UniformSpace.Completion.toComplₗᵢ (𝕜 := ℝ) (E := CameraFinsupp)

/-- The canonical embedding is the ordinary completion coercion. -/
@[simp] theorem cameraEmbedding_apply (u : CameraFinsupp) :
    cameraEmbedding u = (u : CameraHilbert) := rfl

/-- Finitely supported camera coefficients have dense image in the canonical
camera Hilbert space. -/
theorem cameraEmbedding_denseRange : DenseRange cameraEmbedding := by
  change DenseRange ((↑) : CameraFinsupp → CameraHilbert)
  exact UniformSpace.Completion.denseRange_coe

/-- Completion preserves the intrinsic Gram inner product exactly. -/
theorem cameraEmbedding_inner (u v : CameraFinsupp) :
    inner ℝ (cameraEmbedding u) (cameraEmbedding v) = gramForm u v := by
  simp

/-- Completion preserves the intrinsic Gram norm exactly. -/
theorem cameraEmbedding_norm (u : CameraFinsupp) :
    ‖cameraEmbedding u‖ = ‖u‖ :=
  cameraEmbedding.norm_map u

/-- Canonical Hilbert-space vector associated with one native camera. -/
def cameraVector (camera : CameraIndex) : CameraHilbert :=
  cameraEmbedding (Finsupp.single camera 1)

/-- Inner products of canonical camera vectors recover the all-bases Gram
kernel exactly. -/
@[simp] theorem inner_cameraVector (camera₁ camera₂ : CameraIndex) :
    inner ℝ (cameraVector camera₁) (cameraVector camera₂) =
      gramKernel camera₁ camera₂ := by
  simp [cameraVector]

/-- The squared norm of a canonical camera vector is the corresponding Gram
diagonal entry. -/
theorem norm_cameraVector_sq (camera : CameraIndex) :
    ‖cameraVector camera‖ ^ 2 = gramKernel camera camera := by
  rw [InnerProductSpace.norm_sq_eq_re_inner (𝕜 := ℝ)]
  exact inner_cameraVector camera camera

/-- Finite camera level consisting of coefficient vectors supported on labels
at most `bound`. -/
def finiteCameraSubspace (bound : ℕ) : Submodule ℝ CameraFinsupp :=
  Finsupp.supported ℝ ℝ {camera | cameraLabel camera ≤ bound}

/-- Finite camera levels are monotone in their label bound. -/
theorem finiteCameraSubspace_mono {bound₁ bound₂ : ℕ}
    (hbound : bound₁ ≤ bound₂) :
    finiteCameraSubspace bound₁ ≤ finiteCameraSubspace bound₂ := by
  intro u hu
  rw [finiteCameraSubspace, Finsupp.mem_supported] at hu ⊢
  intro camera hcamera
  exact (hu hcamera).trans hbound

/-- Every finite camera level embeds isometrically into the canonical
all-bases camera Hilbert space. -/
def finiteCameraInclusion (bound : ℕ) :
    finiteCameraSubspace bound →ₗᵢ[ℝ] CameraHilbert :=
  cameraEmbedding.comp (finiteCameraSubspace bound).subtypeₗᵢ

/-- Finite-level inclusion is extension by zero followed by completion. -/
@[simp] theorem finiteCameraInclusion_apply (bound : ℕ)
    (u : finiteCameraSubspace bound) :
    finiteCameraInclusion bound u = cameraEmbedding u.1 := rfl

/-- The finite-level inclusions are compatible with increasing the camera
bound. -/
theorem finiteCameraInclusion_mono_apply {bound₁ bound₂ : ℕ}
    (hbound : bound₁ ≤ bound₂) (u : finiteCameraSubspace bound₁) :
    finiteCameraInclusion bound₂
        ⟨u.1, finiteCameraSubspace_mono hbound u.2⟩ =
      finiteCameraInclusion bound₁ u := rfl

/-- The intrinsic inner product on every finite level is preserved exactly by
its inclusion into the all-bases completion. -/
theorem finiteCameraInclusion_inner (bound : ℕ)
    (u v : finiteCameraSubspace bound) :
    inner ℝ (finiteCameraInclusion bound u) (finiteCameraInclusion bound v) =
      gramForm u.1 v.1 := by
  simp

/-- A concrete bound containing the support of a finitely supported camera
coefficient vector. -/
def cameraSupportBound (u : CameraFinsupp) : ℕ :=
  ∑ camera ∈ u.support, cameraLabel camera

/-- Every active camera label lies below the concrete support bound. -/
theorem cameraLabel_le_cameraSupportBound {u : CameraFinsupp}
    {camera : CameraIndex} (hcamera : camera ∈ u.support) :
    cameraLabel camera ≤ cameraSupportBound u := by
  exact Finset.single_le_sum
    (fun other _ => Nat.zero_le (cameraLabel other)) hcamera

/-- Every finitely supported coefficient vector belongs to some finite camera
level. -/
theorem mem_finiteCameraSubspace_cameraSupportBound (u : CameraFinsupp) :
    u ∈ finiteCameraSubspace (cameraSupportBound u) := by
  rw [finiteCameraSubspace, Finsupp.mem_supported]
  intro camera hcamera
  exact cameraLabel_le_cameraSupportBound hcamera

/-- The union of all finite camera levels has dense image in the canonical
all-bases camera Hilbert space.  This is the Hilbert inductive-limit statement
from the research notes. -/
theorem dense_iUnion_range_finiteCameraInclusion :
    Dense (⋃ bound : ℕ, Set.range (finiteCameraInclusion bound)) := by
  apply cameraEmbedding_denseRange.mono
  rintro _ ⟨u, rfl⟩
  apply Set.mem_iUnion.2
  refine ⟨cameraSupportBound u, ?_⟩
  refine ⟨⟨u, mem_finiteCameraSubspace_cameraSupportBound u⟩, rfl⟩

/-- Every canonical camera vector already occurs at every finite level whose
bound contains its label. -/
theorem cameraVector_mem_range_finiteCameraInclusion (camera : CameraIndex)
    {bound : ℕ} (hbound : cameraLabel camera ≤ bound) :
    cameraVector camera ∈ Set.range (finiteCameraInclusion bound) := by
  let coefficient : CameraFinsupp := Finsupp.single camera 1
  have hcoefficient : coefficient ∈ finiteCameraSubspace bound := by
    rw [finiteCameraSubspace, Finsupp.mem_supported]
    intro other hother
    have hotherEq : other = camera := by
      simpa [coefficient, Finsupp.mem_support_iff] using hother
    simpa [hotherEq] using hbound
  exact ⟨⟨coefficient, hcoefficient⟩, rfl⟩

end NativeCarrySpectralWeyl.Infinite
